<link rel="stylesheet" href="../../public/styles/global.css">
<link rel="stylesheet" href="../../public/styles/adm.css">

<div>
  <form method="POST" action="/admin">
    <Select name="metodo_um">
      <option value="genero">genero</option>
      <option value="escola">escola</option>
      <option value="bairro">bairro</option>
    </Select>

    <Select name="metodo_dois">
      <option value="null">Nenhum</option>
    </Select>
    
    <Select name="id_escola">
      <option value="1">CAIC Professor Mariano Costa</option>
      <option value="2">CAIC Professor Desembargador Francisco José R de Oliveira</option>
      <option value="3">CEDUP</option>
      <option value="4">Ceja de Joinville</option>
      <option value="5">Colégio Policial Militar Feliciano Nunes Pires</option>
      <option value="6">Escola Municipal Professor Rosa Maria Berezoski Demarchi</option>
      <option value="7">Escola Municipal Professor Sylvio Sniecikovski</option>
      <option value="8">Escola Municipal Professor Virginia Soares</option>
      <option value="9">Escola Municipal Professor Saul Santanna de Oliveira Dias</option>
      <option value="10">Eeb Arnaldo Moreira Douat</option>
      <option value="11">Eeb Dom Pio de Freitas</option>
      <option value="12">Eeb Dr Georg Keller</option>
      <option value="13">Eeb Dr Jorge Lacerda</option>
      <option value="14">Eeb Dr Paulo Medeiros</option>
      <option value="15">Eeb Dr Tufi Dippe</option>
      <option value="16">Eeb Eng Annes Gualberto</option>
      <option value="17">Eeb Francisco Eberhardt</option>
      <option value="18">Eeb Giovani Pasqualini Faraco</option>
      <option value="19">Eeb João Colin</option>
      <option value="20">Eeb Marli Maria de Souza</option>
      <option value="21">Eeb Olavo Bilac</option>
      <option value="22">Eeb Placido Olimpio de Oliveira</option>
      <option value="23">Eeb Pres Medici</option>
      <option value="24">Eeb Professor Alicia B Ferreira</option>
      <option value="25">Eeb Professor Antonia Alpaides C dos Santos</option>
      <option value="26">Eeb Professor Germano Timm</option>
      <option value="27">Eeb Professor Gertrudes Benta Costa</option>
      <option value="28">Eeb Professor Gustavo Augusto Gonzaga</option>
      <option value="29">Eeb Professor Jandira D Avila</option>
      <option value="30">Eeb Professor João Martins Veras</option>
      <option value="31">Eeb Professor João Rocha</option>
      <option value="32">Eeb Professor Juracy Maria Brosig</option>
      <option value="33">Eeb Professor Maria Amin Ghanem</option>
      <option value="34">Eeb Professor Nair da Silva Pinheiro</option>
      <option value="35">Eeb Professor Rudolfo Meyer</option>
      <option value="36">Eeb Senador Rodrigo Lobo</option>
      <option value="37">Eeb Ver Guilherme Zuege</option>
      <option value="38">Eem Bailarina Liselott Trinks</option>
      <option value="39">Eem Dep Nagib Zattar</option>
      <option value="40">Eem Gov Celso Ramos</option>
      <option value="41">Eem Governador Luiz Henrique da Silveira</option>
      <option value="42">Escola Municipal Monsenhor Sebastiao Scarzello</option>
      <option value="43">Escola Agricola Municipal Carlos Heins Funke</option>
      <option value="44">Escola Municipal Professor João Bernardino da Silveira Jr</option>
      <option value="45">Escola Municipal Adolpho Bartsch</option>
      <option value="46">Escola Municipal Alfredo Germano Henrique Hardt</option>
      <option value="47">Escola Municipal Amador Aguiar</option>
      <option value="48">Escola Municipal Anaburgo</option>
      <option value="49">Escola Municipal Anita Garibaldi</option>
      <option value="50">Escola Municipal Coronel Alire Carneiro</option>
      <option value="51">Escola Municipal de Jovens e Adultos Cesita</option>
      <option value="52">Escola Municipal de Saude Maria Carola Keller</option>
      <option value="53">Escola Municipal Deputado Lauro Carneiro de Loyola</option>
      <option value="54">Escola Municipal Dom Jaime de Barros Camara</option>
      <option value="55">Escola Municipal Doutor Abdon Baptista</option>
      <option value="56">Escola Municipal Doutor José Antonio Navarro Lins</option>
      <option value="57">Escola Municipal Doutor Sadalla Amin Ghanem</option>
      <option value="58">Escola Municipal Dr Hans Dieter Schmidt</option>
      <option value="59">Escola Municipal Dr Ruben Roberto Schmidlin</option>
      <option value="60">Escola Municipal Emilio Paulo Roberto Hardt</option>
      <option value="61">Escola Municipal Enfermeira Hilda Anna Krisch</option>
      <option value="62">Escola Municipal Eugenio Klug</option>
      <option value="63">Escola Municipal Evaldo Koehler</option>
      <option value="64">Escola Municipal Fritz Benkendorf</option>
      <option value="65">Escola Municipal Germano Lenschow</option>
      <option value="66">Escola Municipal Governador Heriberto Hulse</option>
      <option value="67">Escola Municipal Governador Pedro Ivo Campos</option>
      <option value="68">Escola Municipal Hermann Muller</option>
      <option value="69">Escola Municipal João Costa</option>
      <option value="70">Escola Municipal João de Oliveira</option>
      <option value="71">Escola Municipal José do Patrocinio</option>
      <option value="72">Escola Municipal Nelson de Miranda Coutinho</option>
      <option value="73">Escola Municipal Nove de Marco</option>
      <option value="74">Escola Municipal Otto Ristow Filho</option>
      <option value="75">Escola Municipal Padre Valente Simioni</option>
      <option value="76">Escola Municipal Pastor Hans Muller</option>
      <option value="77">Escola Municipal Paul Harris</option>
      <option value="78">Escola Municipal Pauline Parucker</option>
      <option value="79">Escola Municipal Placido Xavier Vieira</option>
      <option value="80">Escola Municipal Prefeito Baltasar Buschle</option>
      <option value="81">Escola Municipal Prefeito Emilio Stock Junior</option>
      <option value="82">Escola Municipal Prefeito Geraldo Wetzel</option>
      <option value="83">Escola Municipal Prefeito Joaquim Felix Moreira</option>
      <option value="84">Escola Municipal Prefeito Luiz Gomes</option>
      <option value="85">Escola Municipal Prefeito Max Colin</option>
      <option value="86">Escola Municipal Prefeito Nilson Wilson Bender</option>
      <option value="87">Escola Municipal Prefeito Wittich Freitag</option>
      <option value="88">Escola Municipal Pres Arthur da Costa e Silva</option>
      <option value="89">Escola Municipal Presidente Castello Branco</option>
      <option value="90">Escola Municipal Professor Ada Santanna da Silveira</option>
      <option value="91">Escola Municipal Professor Edgar Monteiro Castanheira</option>
      <option value="92">Escola Municipal Professor Isabel Silveira Machado</option>
      <option value="93">Escola Municipal Professor Lacy Luiza da Cruz Flores</option>
      <option value="94">Escola Municipal Professor Maria Magdalena Mazzolli</option>
      <option value="95">Escola Municipal Professor Reinaldo Pedro de Franca</option>
      <option value="96">Escola Municipal Professor Thereza Mazzolli Hreisemnou</option>
      <option value="97">Escola Municipal Professor Zulma do Rosario Miranda</option>
      <option value="98">Escola Municipal Professor Alfonso Fiedler</option>
      <option value="99">Escola Municipal Professor Aluizius Sehnem</option>
      <option value="100">Escola Municipal Professor Avelino Marcante</option>
      <option value="101">Escola Municipal Professor Bernardo Tank</option>
      <option value="102">Escola Municipal Professor Francisco Rieper</option>
      <option value="103">Escola Municipal Professor Honorio Saldo</option>
      <option value="104">Escola Municipal Professor João Meerholz</option>
      <option value="105">Escola Municipal Professor José Motta Pires</option>
      <option value="106">Escola Municipal Professor Julio Machado da Luz</option>
      <option value="107">Escola Municipal Professor Orestes Guimaraes</option>
      <option value="108">Escola Municipal Professor Oswaldo Cabral</option>
      <option value="109">Escola Municipal Professora Anna Maria Harger</option>
      <option value="110">Escola Municipal Professora Eladir Skibinski</option>
      <option value="111">Escola Municipal Professora Elizabeth Von Dreifuss</option>
      <option value="112">Escola Municipal Professora Karin Barkemeyer</option>
      <option value="113">Escola Municipal Professora Laura Andrade</option>
      <option value="114">Escola Municipal Professora Maria Regina Leal</option>
      <option value="115">Escola Municipal Professora Rosangela Martinowsky Baptista</option>
      <option value="116">Escola Municipal Professora Senhorinha Soares</option>
      <option value="117">Escola Municipal Professora Valesca May Engelmann</option>
      <option value="118">Escola Municipal Senador Carlos Gomes de Oliveira</option>
      <option value="119">Escola Municipal Sete de Setembro</option>
      <option value="120">Escola Municipal Valentim João da Rocha</option>
      <option value="121">Escola Municipal Vereador Arinor Vogelsanger</option>
      <option value="122">Escola Municipal Vereador Curt Alvino Monich</option>
      <option value="123">Escola Municipal Vereador Hubert Hubener</option>
      <option value="124">IFSC</option>
      <option value="125">Apiscae</option>
      <option value="126">Associação de Amigos do Autista</option>
      <option value="127">Associação Joinvilense Integ do Def Visual</option>
      <option value="128">Associação Educacional Luterana Bom Jesus Ielusc</option>
      <option value="129">Centro de Ed Aldeia do Sol</option>
      <option value="130">Centro de Educação Professor Neide Kruger</option>
      <option value="131">Centro Educacional Conde Modesto Leal</option>
      <option value="132">Centro Educacional Catolica Machado de Assis</option>
      <option value="133">Centro Educacional Conexao</option>
      <option value="134">Centro Educacional Mae Natureza</option>
      <option value="135">Centro Educacional Micherrot</option>
      <option value="136">Colégio 4ª Dimensao</option>
      <option value="137">Colégio Aquarela</option>
      <option value="138">Colégio Bonja Unidade I</option>
      <option value="139">Colégio Bonja Unidade Iii</option>
      <option value="140">Colégio Cenecista José Elias Moreira</option>
      <option value="141">Colégio dos Santos Anjos</option>
      <option value="142">Colégio Evangelico Pastor Manoel Germano de Miranda</option>
      <option value="143">Colégio Exathum</option>
      <option value="144">Colégio Oficina</option>
      <option value="145">Colégio Positivo</option>
      <option value="146">Colégio Santo Antonio</option>
      <option value="147">Colégio Siloe</option>
      <option value="148">Colégio Univille</option>
      <option value="149">Escola Adventista - Bom Retiro</option>
      <option value="150">Escola Adventista - Centro</option>
      <option value="151">Escola Adventista - Costa e Silva</option>
      <option value="152">Escola Alfa Joinville</option>
      <option value="153">CORE - Escola Internacional</option>
      <option value="154">Escola Mais</option>
      <option value="155">Escola Nova Geracao</option>
      <option value="156">Escola Proeza do Saber</option>
      <option value="157">Escola Querubim</option>
      <option value="158">Escola Relicario de Luz</option>
      <option value="159">Escola Risos e Rabiscos</option>
      <option value="160">Escola Tecnica Advance Internacional</option>
      <option value="161">Escola Tecnica Tupy</option>
      <option value="162">Escola Vida Nova</option>
      <option value="163">Exathum Curso e Colégio</option>
      <option value="164">Ibdi Escola de Formacao Profissional</option>
      <option value="165">Inst Educ Esp Profª Lia R S J de Santis</option>
      <option value="166">Instituicao Adventista Sul Brasileira de Educação</option>
      <option value="167">Instituto Escola do Teatro Bolshoi No Brasil</option>
      <option value="168">Instituto Referencia Em Educação Integrada</option>
      <option value="169">Instituto Tecnologico Assessoritec</option>
      <option value="170">SENAC</option>
      <option value="171">Uni Duni Te Jardim Escola</option>
      <option value="172">Escola SESI de Referência</option>
    </Select>

    <Select name="id_bairro">
      <option value="1">Nova Brasília</option>
      <option value="2">Morro do Meio</option>
      <option value="3">São Marcos</option>
      <option value="4">Vila Nova</option>
      <option value="5">Aventureiro</option>
      <option value="6">Comasa</option>
      <option value="7">Espinheiros</option>
      <option value="8">Iririú</option>
      <option value="9">Jardim Iririú</option>
      <option value="10">Vila Cubatão</option>
      <option value="11">Zona Industrial Tupy</option>
      <option value="12">América</option>
      <option value="13">Atiradores</option>
      <option value="14">Bom Retiro</option>
      <option value="15">Centro</option>
      <option value="16">Costa e Silva</option>
      <option value="17">Dona Francisca</option>
      <option value="18">Glória</option>
      <option value="19">Jardim Paraíso</option>
      <option value="20">Jardim Sofia</option>
      <option value="21">Pirabeiraba</option>
      <option value="22">Rio Bonito</option>
      <option value="23">Saguaçu</option>
      <option value="24">Santo Antônio</option>
      <option value="25">Zona Industrial Norte</option>
      <option value="26">Adhemar Garcia</option>
      <option value="27">Anita Garibaldi</option>
      <option value="28">Boehmerwald</option>
      <option value="29">Fátima</option>
      <option value="30">Floresta</option>
      <option value="31">Guanabara</option>
      <option value="32">Itaum</option>
      <option value="33">Itinga</option>
      <option value="34">Jarivatuba</option>
      <option value="35">João Costa</option>
      <option value="36">Paranaguamirim</option>
      <option value="37">Parque Guarani</option>
      <option value="38">Petrópolis</option>
      <option value="39">Profipo</option>
      <option value="40">Santa Catarina</option>
      <option value="41">Ulysses Guimarães</option>
      <option value="42">Boa Vista</option>
      <option value="43">Bucarein</option>
    </Select>


    <button type="submit">Gerar gráfico</button>
  </form>

</div>

